WebPetAppShop/Controllers/FavoriteController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db;
using System;
using System.Collections.Generic;
using WebPetAppShop.Models;

namespace WebPetAppShop.Controllers;

public class FavoriteController : Controller
{
    private readonly IFavoriteRepos favoriteRepos;
    private readonly IProductRepos productRepos;
    private readonly IMapper mapper;

    public FavoriteController(IFavoriteRepos favoriteRepos, IProductRepos productRepos, IMapper mapper)
    {
        this.favoriteRepos = favoriteRepos;
        this.productRepos = productRepos;
        this.mapper = mapper;
    }

    public IActionResult Index()
    {
        var products = this.favoriteRepos.GetAll(Constans.UserId);
        return View(this.mapper.Map<List<ProductViewModel>>(products));
    }

    public IActionResult Add(Guid productId)
    {
        var product = this.productRepos.TryByGuid(productId);
        this.favoriteRepos.Add(Constans.UserId, product);

        return RedirectToAction(nameof(Index));
    }

    public IActionResult Remove(Guid productId)
    {
        this.favoriteRepos.Remove(Constans.UserId, productId);

        return RedirectToAction(nameof(Index));
    }
}

WebPetAppShop/Controllers/OrderController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db;
using OnlineShop.Db.Model;
using WebPetAppShop.Models;

namespace WebPetAppShop.Controllers
{
    public class OrderController : Controller
    {
        private readonly ICartRepos cartRepos;
        private readonly IOrderRepos orderRepos;
        private readonly IMapper mapper;

        public OrderController(ICartRepos cartRepos, IOrderRepos orderRepos, IMapper mapper)
        {
            this.cartRepos = cartRepos;
            this.orderRepos = orderRepos;
            this.mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Buy(UserDeliveryInfoViewModel userInfo)
        {
            if (!ModelState.IsValid)
            {
                return View(nameof(Index), userInfo);
            }

            var existCart = this.cartRepos.TyGetByUserId(Constans.UserId);

            var order = new Order
            {
                UserInfo = this.mapper.Map<UserDeliveryInfo>(userInfo), // маппинг моделей
                Items = existCart.Items,
            };

            if (existCart != null)
            {
                this.orderRepos.Add(order);
            }

            this.cartRepos.Clear(Constans.UserId);

            return View(nameof(Buy));
        }
    }
}

WebPetAppShop/Views/Shared/Components/Cart/CartViewComponent.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db;
using WebPetAppShop.Models;

namespace WebPetAppShop.Views.Shared.Components.Cart
{
    public class CartViewComponent : ViewComponent
    {
        private readonly ICartRepos cartRepos;
        private readonly IMapper mapper;

        public CartViewComponent(ICartRepos cartRepos, IMapper mapper)
        {
            this.cartRepos = cartRepos;
            this.mapper = mapper;
        }

        public IViewComponentResult Invoke()
        {
            var cartDb = cartRepos.TyGetByUserId(Constans.UserId);
            var catViewModel = mapper.Map<CartViewModel>(cartDb); // маппинг моделей
            var productCounts = catViewModel?.Amount ?? 0;

            return View("Cart", productCounts);
        }
    }
}

WebPetAppShop/Views/Shared/Components/FavoriteProductsCount/FavoriteProductsCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db;

namespace WebPetAppShop.Views.Shared.Components.FavoriteProductsCount
{
    public class FavoriteProductsCountViewComponent : ViewComponent
    {
        private readonly IFavoriteRepos favoriteRepos;

        public FavoriteProductsCountViewComponent(IFavoriteRepos favoriteRepos)
        {
            this.favoriteRepos = favoriteRepos;
        }

        public IViewComponentResult Invoke()
        {
            var producCounts = this.favoriteRepos.GetAll(Constans.UserId).Count;

            return View("FavoriteProductsCount", producCounts);
        }
    }
}

WebPetAppShop/Views/Shared/Footer.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2025 - WebPetAppShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

WebPetAppShop/Views/Shared/Header.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebPetAppShop</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Корзина @await Component.InvokeAsync("Cart")</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Войти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Order" asp-action="Index">Администратор</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Favorite" asp-action="Index">Избранное @await Component.InvokeAsync("FavoriteProductsCount")</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

WebPetAppShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebPetAppShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    @await Html.PartialAsync("Header")

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @await Html.PartialAsync("Footer")

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await Html.PartialAsync("_ValidationScriptsPartial")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>