WebPetAppShop/Controllers/CartController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db;
using System;
using WebPetAppShop.Models;

namespace WebPetAppShop.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductRepos productRepos;
        private readonly ICartRepos cartRepos;
        private readonly IMapper mapper;

        public CartController(IProductRepos productRepos, ICartRepos cartRepos, IMapper mapper)
        {
            this.productRepos = productRepos;
            this.cartRepos = cartRepos;
            this.mapper = mapper;
        }

        public IActionResult Index()
        {
            var cartDb = this.cartRepos.TyGetByUserId(Constans.UserId);
            var cartViewModel = mapper.Map<CartViewModel>(cartDb); // маппинг моделей

            return View(nameof(Index), cartViewModel);
        }

        public IActionResult Add(Guid productId)
        {
            var productDb = this.productRepos.TryByGuid(productId);
            this.cartRepos.Add(productDb, Constans.UserId);

            return RedirectToAction(nameof(Index)); // повторный вызов Index
        }

        public IActionResult DecreasItemAmount(Guid productId)
        {
            this.cartRepos.DecreasItem(productId, Constans.UserId);

            return RedirectToAction(nameof(Index)); // повторный вызов Index
        }

        public IActionResult Clear(Guid productId)
        {
            this.cartRepos.Clear(Constans.UserId);

            return RedirectToAction(nameof(Index)); // повторный вызов Index
        }
    }
}

WebPetAppShop/Controllers/FavoriteController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db;
using System;
using System.Collections.Generic;
using WebPetAppShop.Models;

namespace WebPetAppShop.Controllers;

public class FavoriteController : Controller
{
    private readonly IFavoriteRepos favoriteRepos;
    private readonly IProductRepos productRepos;
    private readonly IMapper mapper;

    public FavoriteController(IFavoriteRepos favoriteRepos, IProductRepos productRepos, IMapper mapper)
    {
        this.favoriteRepos = favoriteRepos;
        this.productRepos = productRepos;
        this.mapper = mapper;
    }

    public IActionResult Index()
    {
        var products = this.favoriteRepos.GetAll(Constans.UserId);
        return View(this.mapper.Map<List<ProductViewModel>>(products));
    }

    public IActionResult Add(Guid productId)
    {
        var product = this.productRepos.TryByGuid(productId);
        this.favoriteRepos.Add(Constans.UserId, product);

        return RedirectToAction(nameof(Index));
    }

    public IActionResult Remove(Guid productId)
    {
        this.favoriteRepos.Remove(Constans.UserId, productId);

        return RedirectToAction(nameof(Index));
    }
}

WebPetAppShop/Controllers/HomeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db;
using System.Collections.Generic;
using WebPetAppShop.Models;

namespace WebPetAppShop.Controllers;

public class HomeController : Controller
{
    private readonly IProductRepos productRepos;
    private readonly IMapper mapper;

    public HomeController(IProductRepos productRepos, IMapper mapper)
    {
        this.productRepos = productRepos;
        this.mapper = mapper;
    }

    public IActionResult Index(string name)
    {
        var productsDb = productRepos.GetAll();
        var productsViewModel = this.mapper.Map<List<ProductViewModel>>(productsDb);

        return View(nameof(Index), productsViewModel);
    }
}

WebPetAppShop/Controllers/ProductController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db;
using System;
using WebPetAppShop.Models;

namespace WebPetAppShop.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepos productRepos;
        private readonly IMapper mapper;

        public ProductController(IProductRepos productRepos, IMapper mapper)
        {
            this.productRepos = productRepos;
            this.mapper = mapper;
        }

        public IActionResult Index(Guid guid)
        {
            var productDb = this.productRepos?.TryByGuid(guid);
            var productViewModel = this.mapper.Map<ProductViewModel>(productDb); // маппинг моделей

            return View(nameof(Index), productViewModel);
        }
    }
}

WebPetAppShop/Views/Home/Index.cshtml
@model List<ProductViewModel>;

@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-lg-3">
        <h4 class="my-4">Название магазина</h4>
        <div class="list-group">
            <a class="list-group-item" asp-area="" asp-controller="" asp-action="">Активный элемент</a>
            <a class="list-group-item" asp-area="" asp-controller="" asp-action="">Второй элемент</a>
            <a class="list-group-item" asp-area="" asp-controller="" asp-action="">Третий элемент</a>
            <a class="list-group-item" asp-area="" asp-controller="" asp-action="">Четвертый элемент</a>
            <a class="list-group-item" asp-area="" asp-controller="" asp-action="">И пятый</a>
        </div>
    </div>

    <div class="col-lg-9">
        <div id="carouselExampleIndicators" class="carousel slide my-4">
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="~/images/asp.png" class="d-block img-fluid" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="~/images/c-.png" class="d-block img-fluid" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="~/images/c-sharp.png" class="d-block img-fluid" alt="...">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Предыдущий</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Следующий</span>
            </button>
        </div>
        <div class="row">
            @foreach (var product in Model)
            {
                <div class="col-lg-3 col-md-6 mb-4">
                    <div class="card h-100 box-shadow">
                        <a asp-area="" asp-controller="Product" asp-action="Index" asp-route-guid="@product.Id"><img class="card-img-top" src=@product.ImagePath alt="Изображение товара" /></a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a asp-area="" asp-controller="Product" asp-action="Index" asp-route-guid="@product.Id">@product.Name</a>
                            </h4>
                            <h5>@product.Cost$</h5>
                            <p class="card-text">@product.Description</p>

                        </div>
                        <div class="card-body d-flex flex-column align-items-end justify-content-center">
                            <a class="btn btn-primary mb-2 w-100" asp-area="" asp-controller="Cart" asp-action="Add" asp-route-productId="@product.Id"
                               role="button">Добавить в корзину</a>
                            <a class="btn btn-success w-100" asp-area="" asp-controller="Favorite" asp-action="Add" asp-route-productId="@product.Id"
                               role="button">Добавить в избранное</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>